### PR TITLE
HTML5 & Marx CSS Redesign

### PR DESCRIPTION
**Pull request by griffenedge**
- Migrated to HTML5
- Made the HTML more semantic
- Added [Marx](https://mblode.github.io/marx/) and a consistent navbar to the 3 main pages
- Moved all images into img folder
- Ran all images through ImageOptim at 100% quality and lossless to reduce file sizes
- Added favicon based on app icon

### CODE REVIEW

**Comment by shlomif** [comment]
Hi Griffen,

thanks, but:

1. Please use XHTML5 instead of HTML5. The original version was XHTML as well.

2. Please do not indent the XHTML tags, because it both bloats the page and
results in larger diffs.

In the future, we may wish to convert the site to an SSG (see
https://shlomif-tech.livejournal.com/74922.html ).

Regards,

@shlomif

 On Tue, 31 Jul 2018 08:40:26 -0700
Griffen <notifications@github.com> wrote:

> - Migrated to HTML5
> - Made the HTML more semantic
> - Added [Marx](https://mblode.github.io/marx/) and a consistent navbar to the
> 3 main pages
> - Moved all images into img folder
> - Ran all images through ImageOptim at 100% quality and lossless to reduce
> file sizes
> - Added favicon based on app icon
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/shlomif/pysolfc-website/pull/1
> 
> -- Commit Summary --
> 
>   * HTML5 & Marx CSS
>   * ImageOptim
> 
> -- File Changes --
> 
>     D htdocs/PySolFC-Fedora-25-Xfce--shlomif.png (0)
>     M htdocs/all_games.html (9908)
>     D htdocs/castle.jpg (0)
>     A htdocs/css/custom.min.css (1)
>     A htdocs/css/marx.min.css (2)
>     M htdocs/doc/images/c.gif (0)
>     M htdocs/doc/images/camelot-goal.gif (0)
>     M htdocs/doc/images/pysollogo00.gif (0)
>     M htdocs/doc/images/pysollogo01.gif (0)
>     M htdocs/doc/images/pysollogo02.gif (0)
>     M htdocs/doc/images/pysollogo03.gif (0)
>     A htdocs/favicon.ico (0)
>     D htdocs/freecell-pil.png (0)
>     D htdocs/freecell-tk.png (0)
>     D htdocs/freecell-ttk.png (0)
>     A htdocs/img/PySolFC-Fedora-25-Xfce--shlomif.png (0)
>     A htdocs/img/freecell-pil.png (0)
>     A htdocs/img/freecell-tk.png (0)
>     A htdocs/img/freecell-ttk.png (0)
>     A htdocs/img/header.png (0)
>     A htdocs/img/logo.png (0)
>     A htdocs/img/nostalgy.png (0)
>     M htdocs/index.html (483)
>     M htdocs/screenshots.html (67)
> 
> -- Patch Links --
> 
> https://github.com/shlomif/pysolfc-website/pull/1.patch
> https://github.com/shlomif/pysolfc-website/pull/1.diff
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Humanity - Parody of Modern Life - http://shlom.in/humanity

Linux — Because Software Problems Should not Cost Money.
    — http://www.shlomifish.org/art/linux_banner/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@griffedge : and please use relative links instead of absolute ones. A file:/// viewing cannot find the CSS.

**Comment by griffenedge** [comment]
Hey Shlomi,
Happy to implement these changes, but was wondering:
- Why XHTML5 instead of HTML5?
- What you meant by relative links instead of absolute. Do you mean not accessing files from the root?

**Comment by griffedge** [comment]
1.

**Comment by shlomif** [comment]
Hi,

On Wed, 01 Aug 2018 06:06:10 -0700
Griffen <notifications@github.com> wrote:

> Hey Shlomi,
> Happy to implement these changes, 

Thanks!

> but was wondering what you meant by
> relative links instead of absolute. Do you mean not accessing files from the
> root?
> 

Yes, instead of «href="/css/f.css"» do «href="css/f.css"» - or ".." - just
without a leading slash.



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Chuck Norris/etc. Facts - http://www.shlomifish.org/humour/bits/facts/

Cast your bread upon the waters, for after many days you will find it again.
    — Ecclesiastes 1:11

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
I prefer XHTML over HTML because it is stricter and less ambiguous and because it can be parsed and processed by XML parsers/etc.

**Comment by shlomif** [comment]
@griffedge : any news? are you working on it?

**Comment by griffenedge** [comment]
Sorry @shlomif, I've been busy the past week. I'm still working on it and may need a little assistance with XHTML.

**Comment by shlomif** [comment]
On Wed, 08 Aug 2018 17:18:22 -0700
Griffen <notifications@github.com> wrote:

> Sorry @shlomif, I've been busy the past week. I'm still working on it and may
> need a little assistance with XHTML.
> 

OK, thanks for the update. See
https://stackoverflow.com/questions/1415394/what-differences-are-expected-of-xhtml5-versus-html5



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
List of Text Processing Tools - http://shlom.in/text-proc

Barth's Distinction:  There are two types of people: those who divide people
into two types, and those who don't.
    — via fortune-mod.

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by griffenedge** [comment]
Regarding unindenting elements, did you still want to keep the list indents that are in 134a135?

**Comment by shlomif** [comment]
On Fri, 10 Aug 2018 23:06:43 -0700
Griffen <notifications@github.com> wrote:

> Regarding unindenting elements, did you still want to keep the list indents
> that are in 134a135?
> 

you can get rid of them. thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
UNIX Fortune Cookies - http://www.shlomifish.org/humour/fortunes/

I hope that if it had not been clear before, it isn’t less clear now.
    — One of Shlomi Fish’s Technion Lecturers

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@griffedge There are some conflicts - can you resolve them?

**Comment by shlomif** [comment]
Merged, thanks!

**Comment by griffenedge** [comment]
Great! I just noticed that the .htaccess file hasn't been set up to allow linked pages without the .html extension. This means currently all the internal links on the site won't work. If you follow the instructions in this it's a very easy fix https://stackoverflow.com/questions/16919526/how-to-link-to-pages-without-the-html-extension

**Pull request merged**
